### PR TITLE
Checkout from gcc-10.2.0 tag to avoid build failure on gcc-10 branch

### PR DESCRIPTION
**Pull request by pkoshevoy**
gcc-10git failed to build, probably due to https://github.com/gcc-mirror/gcc/commit/3ec6a380bda3d2193925e1c017ea2739476cc125

### CODE REVIEW

**Comment by Zeranoe** [comment]
Thanks for the PR, can you provide the error you got?

**Comment by pkoshevoy** [comment]
> Thanks for the PR, can you provide the error you got?

```g++ -c   -g -O2 -DIN_GCC  -DCROSS_DIRECTORY_STRUCTURE   -fno-exceptions -fno-rtti -fasynchronous-unwind-tables -W -Wall -Wno-narrowing -Wwrite-strings -Wcast-qual -Wmissing-format-attribute -Woverloaded-virtual -pedantic -Wno-long-long -Wno-variadic-macros -Wno-overlength-strings   -DHAVE_CONFIG_H  -DGENERATOR_FILE -fno-PIE -I. -Ibuild -I../../../src/gcc-10git/gcc -I../../../src/gcc-10git/gcc/build -I../../../src/gcc-10git/gcc/../include  -I../../../src/gcc-10git/gcc/../libcpp/include  \
	-o build/gencheck.o ../../../src/gcc-10git/gcc/gencheck.c
In file included from ./tm.h:20:0,
                 from ../../../src/gcc-10git/gcc/gencheck.c:23:
../../../src/gcc-10git/gcc/config/i386/i386.h:2481:46: error: 'PTA_CLDEMOTE' was not declared in this scope
   | PTA_GFNI | PTA_MOVDIRI | PTA_MOVDIR64B | PTA_CLDEMOTE | PTA_WAITPKG;
                                              ^
../../../src/gcc-10git/gcc/config/i386/i386.h:2480:24: warning: 'PTA_TREMONT' defined but not used [-Wunused-variable]
 const wide_int_bitmask PTA_TREMONT = PTA_GOLDMONT_PLUS | PTA_CLWB
                        ^
Makefile:2723: recipe for target 'build/gencheck.o' failed
make[1]: *** [build/gencheck.o] Error 1```

**Comment by pkoshevoy** [comment]
if there is no interest I'll close the PR

**Comment by Zeranoe** [comment]
Sorry for the delay, but first tests here build all the way through.

Can you try again? Perhaps this was address upstream. If it still fails, can you provide your system and package details?

**Comment by pkoshevoy** [comment]
> Sorry for the delay, but first tests here build all the way through.
> 
> Can you try again? Perhaps this was address upstream. If it still fails, can you provide your system and package details?

It was a docker image based on ubuntu 16.04 ... I can no longer reproduce the problem, so it appears it was fixed in the gcc upstream

**Pull request closed without merging**
